version: '3'

services:
  ziplink:
    container_name: ziplink
    build:
      context: .
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8080:8080"
    depends_on:
      - database
    networks:
      - backend

  database:
    container_name: ziplink-database
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ziplink
      POSTGRES_USER: ziplink_admin
      POSTGRES_PASSWORD: 123456789
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - backend

networks:
  backend:
    driver: bridge
volumes:
  db: