version: '3'

services:
  database:
    container_name: ziplink-database
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ziplink
      POSTGRES_USER: ziplink_admin
      POSTGRES_PASSWORD: 123456789
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db: