ziplink:
  short-url-config:
    base-url: ${SHORT_BASE_URL}
    length: 12

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

